In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5309, 6323, 6429, 4941],
 [5309, 6323, 6429, 9875],
 [5309, 6409, 6429, 9493],
 [140, 3903, 968, 8767, 6046],
 [140, 3903, 968, 8767, 2288],
 [7584, 5309, 3475, 6429, 4204],
 [3051, 3466, 6544, 8767]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5309 6323 6429 4941]
 [   0    0    0    0 5309 6323 6429 9875]
 [   0    0    0    0 5309 6409 6429 9493]
 [   0    0    0  140 3903  968 8767 6046]
 [   0    0    0  140 3903  968 8767 2288]
 [   0    0    0 7584 5309 3475 6429 4204]
 [   0    0    0    0 3051 3466 6544 8767]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 171ms/step


array([[[-2.7350342e-02,  2.4105910e-02,  3.8585152e-02, -1.4128327e-02,
          2.2211622e-02, -4.7323178e-02,  9.8147616e-03,  4.2598788e-02,
          2.4204638e-02,  3.6416020e-02],
        [-2.7350342e-02,  2.4105910e-02,  3.8585152e-02, -1.4128327e-02,
          2.2211622e-02, -4.7323178e-02,  9.8147616e-03,  4.2598788e-02,
          2.4204638e-02,  3.6416020e-02],
        [-2.7350342e-02,  2.4105910e-02,  3.8585152e-02, -1.4128327e-02,
          2.2211622e-02, -4.7323178e-02,  9.8147616e-03,  4.2598788e-02,
          2.4204638e-02,  3.6416020e-02],
        [-2.7350342e-02,  2.4105910e-02,  3.8585152e-02, -1.4128327e-02,
          2.2211622e-02, -4.7323178e-02,  9.8147616e-03,  4.2598788e-02,
          2.4204638e-02,  3.6416020e-02],
        [ 4.3915343e-02, -3.3367887e-02, -3.9863370e-02, -1.9160081e-02,
          4.1050505e-02,  4.3798957e-02,  1.8325042e-02, -4.4911053e-02,
         -4.5675147e-02,  3.3935476e-02],
        [ 2.5632862e-02,  5.4292791e-03, -3.9830528e-02,  1.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5309, 6323, 6429, 4941])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [ 0.04391534, -0.03336789, -0.03986337, -0.01916008,  0.0410505 ,
         0.04379896,  0.01832504, -0.04491105, -0.04567515,  0.03393548],
       [ 0.02563286,  0.00542928, -0.03983053,  0.01691523,  0.04606367,
        -0.00396226, -0.01949039, -0.04081681, -0.02117493, -0.00796237],
       [ 0.0213925 , -0.02462224,  0.04693402,  0.03066898,  0.03461409,
        -0.01061808,  0.0325128 , -0.02322413

In [ ]:
model.predict(embedded_docs[1])
##This will output the predicted vector representation for the 2nd document in the embedded_docs list.

1/1 [==============================] - 0s 120ms/step


array([[-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [ 0.04391534, -0.03336789, -0.03986337, -0.01916008,  0.0410505 ,
         0.04379896,  0.01832504, -0.04491105, -0.04567515,  0.03393548],
       [ 0.02563286,  0.00542928, -0.03983053,  0.01691523,  0.04606367,
        -0.00396226, -0.01949039, -0.04081681, -0.02117493, -0.00796237],
       [ 0.0213925 , -0.02462224,  0.04693402,  0.03066898,  0.03461409,
        -0.01061808,  0.0325128 , -0.02322413

In [ ]:
model.predict(embedded_docs[6])
##This will output the predicted vector representation for the 7th document in the embedded_docs list.

1/1 [==============================] - 0s 48ms/step


array([[-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [-0.02735034,  0.02410591,  0.03858515, -0.01412833,  0.02221162,
        -0.04732318,  0.00981476,  0.04259879,  0.02420464,  0.03641602],
       [ 0.0478541 ,  0.00044314,  0.000282  , -0.03334148, -0.00391233,
         0.03175067, -0.01420392, -0.04625831,  0.04992563,  0.01512324],
       [-0.0022589 ,  0.04099372, -0.04487174,  0.03674394,  0.01912817,
         0.00831831, -0.02703546, -0.04434437, -0.01396609,  0.00949185],
       [-0.00772871, -0.00216372, -0.01596379, -0.00781747, -0.01972328,
         0.0213259 ,  0.01512685, -0.03609004